# docker-compose.yml
services:
  web:
    build: .  # Use Dockerfile in the current directory
    container_name: apache_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/ifos_v1                 # Mount application files
      - ./logs/apache:/var/log/apache2           # Mount Apache logs to the host
      - ./my.conf:/etc/apache2/conf-enabled/my.conf
