version: '3.8'

services:
  web:
    build:
      context: .     # Use current directory for Dockerfile
    container_name: codeigniter_app
    ports:
      - "8080:80"    # Map port 8080 on your host to port 80 in the container
    volumes:
      - .:/var/www/html  # Mount the current directory to the container
